########################
# Kandan settings file
########################


# What should be used for broadcasting messages to browser?
# valid options: Faye
:broadcaster:
  :name: "Faye"

:per_page: 30

:max_rooms: 99

:public_site: true

# Change [hostname] and [port]
:avatar_url: http://[hostname]:[port]/avatar_image/download/%{hash}
:avatar_fallback: identicon

:now_threshold: 3000
:timestamp_refresh_interval: 2000
